### ISSUE TITLE
Test failures after cloning

### ISSUE THREAD

**Issue by taylorbrooks** [Zensavona/elixtagram#1]
After initially pulling down the library and running the tests, I got 11 failures.

They all appear to fail around the same thing:

``` elixir

 11) test get feed for user (explicitly authenticated) (ElixtagramTest)
     test/elixtagram_test.exs:497
     ** (ArgumentError) argument error
     stacktrace:
       (stdlib) :unicode.characters_to_binary([nil])
       (elixir) lib/list.ex:555: List.to_string/1
       (elixtagram) lib/elixtagram/api/base.ex:78: Elixtagram.API.Base.params_join/2
       (elixtagram) lib/elixtagram/api/base.ex:66: Elixtagram.API.Base.build_url/2
       (elixtagram) lib/elixtagram/api/base.ex:13: Elixtagram.API.Base.get/3
       (elixtagram) lib/elixtagram/api/users.ex:48: Elixtagram.API.Users.feed/2
       test/elixtagram_test.exs:501
```

I haven't investigated much, but I'm guessing that you need to have a true API client with valid credentials to run the tests?

**Comment by Zensavona** [comment]
Actually you don't, all the server responses are recorded with ExVCR, but what I didn't think of at the time is that it will still look for Application/ENV vars containing the credentials for the 'explicitly authenticated' tests.

I'll find a fix for that, it's not ideal really to need to supply credentials to run the tests. Thanks for bringing it to my attention :+1:

**Comment by Zensavona** [comment]
@taylorbrooks if you update to `0.1.3` or do a `git pull` the tests should run fine now with no credentials :smiley:

**Comment by taylorbrooks** [comment]
@Zensavona that did it! awesome turnaround.
