### ISSUE TITLE
Allow to use poison ~> 2.0

### ISSUE THREAD

**Issue by radzserg** [Zensavona/elixtagram#12]
Can you upgrade deps in order to allow using of poison 2. A lot of existing popular packages requires 2.0  

Failed to use "poison" (versions 2.0.0 to 2.2.0) because
  deps/mailgun/mix.exs requires ~> 1.4 or ~> 2.0
  ecto (version 2.0.4) requires ~> 1.5 or ~> 2.0
  elixtagram (version 0.2.9) requires ~> 1.5
  oauth2 (version 0.6.0) requires ~> 1.3 or ~> 2.0
  phoenix (version 1.2.1) requires ~> 1.5 or ~> 2.0

**Comment by Zensavona** [comment]
done :)
