### ISSUE TITLE
Bump oauth2 to 0.8.0

### ISSUE THREAD

**Issue by radzserg** [Zensavona/elixtagram#14]
Would you mind to bump  (probably to 0.3.1) with upgraded
  {:oauth2, "~> 0.8.0"},

I'm using ueberauth for FB and Instagram for authorization
https://github.com/ueberauth/ueberauth_facebook/blob/master/mix.exs#L28
They used 0.6.0 and now uses 0.8.0 
Mix cannot resolve/override dependencies. 
Thank you

**Comment by Zensavona** [comment]
Hi mate, sorry about the slowness in reply to this - I have seen it and I'll get onto it today sometime :)

Thanks

**Comment by Zensavona** [comment]
Sorry about this, totally forgot. Fixed in `0.4.0`
